import { describe, expect, it } from 'vitest';
import { PARAMETRIC_CASE_V1, PARAMETRIC_HAND_SET_V1, PARAMETRIC_HAND_V1, validateParametricCaseV1, validateParametricDialV1, validateParametricHandV1, validateParametricPusherV1, type ParametricCaseV1, type ParametricDialV1, type ParametricHandV1, type ParametricHandSetV1, type ParametricPusherV1 } from '@/domain/geometry/parametric';

const u = { status: 'unknown' as const };
const pusherZero = { pusherCount: 0, pusherLayout: 'none' as const, pusherAngularOffsetDeg: 0, pusherTubeRadius: 0, pusherTubeLength: 0, pusherTubeEmbed: 0, pusherBossRadius: 0, pusherBossLength: 0, pusherBossEmbed: 0 };
const baseCase = (): ParametricCaseV1 => ({ schema: PARAMETRIC_CASE_V1, ...Object.fromEntries(['caseDiameter','midcaseHeight','lugWidth','lugToLug','dialOpening','crystalSeatDiameter','casebackOpening','upperCaseRadiusReduction','lowerCaseRadiusReduction','middleCaseBulge','bezelLipHeight','casebackLipHeight','lugRootWidth','lugTipWidth','lugPairGap','lugCaseOverlap','lugTipDrop','lugThickness','lugTaperStrength','crownTubeRadius','crownTubeLength','crownBossRadius','crownBossLength','crownBossEmbed','crownTubeEmbed'].map(k => [k, 1])), ...pusherZero, caseDiameter: 40, lugToLug: 42, lugWidth: 6, lugTipWidth: 5, dialOpening: 30, crystalSeatDiameter: 32 } as ParametricCaseV1);
const hand = (): ParametricHandV1 => ({ schema: PARAMETRIC_HAND_V1, hub: { diameter: 2, thickness: 0.2, pinionHoleDiameter: 0.5 }, body: { length: 10, rootWidth: 1, distalWidth: 0.5, thickness: 0.1 }, tip: { style: 'POINT', length: 2, width: 0.5, shoulderSweep: 0, lume: true }, tail: { style: 'NONE', length: 0, width: 0, lume: false }, lume: { body: true, tip: false, tail: false } });
describe('parametric contracts', () => { it('exposes versions and validates known case/hand', () => { expect(PARAMETRIC_HAND_SET_V1).toBe('parametric-hand-set/v1'); expect(validateParametricCaseV1(baseCase()).status).toBe('valid'); expect(validateParametricHandV1(hand()).status).toBe('valid'); }); it('distinguishes invalid from unknown', () => { const c = baseCase(); c.caseDiameter = 0; expect(validateParametricCaseV1(c).status).toBe('invalid'); const h = hand(); h.hub.pinionHoleDiameter = u; expect(validateParametricHandV1(h).status).toBe('unknown'); }); it('supports variants, independent lume, and optional seconds', () => { const h = hand(); h.tip.style = 'TRIANGLE'; h.tail.style = 'COUNTERWEIGHT'; expect(h.lume).toEqual({ body: true, tip: false, tail: false }); const set: ParametricHandSetV1 = { schema: PARAMETRIC_HAND_SET_V1, hour: h, minute: h }; expect(set.seconds).toBeUndefined(); }); it('validates chronograph pusher configurations', () => { const c = baseCase(); c.pusherCount = 2; c.pusherLayout = '2h-4h'; c.pusherTubeRadius = 0.9; c.pusherTubeLength = 1.8; c.pusherTubeEmbed = 1.2; c.pusherBossRadius = 1.4; c.pusherBossLength = 1.0; c.pusherBossEmbed = 1.2; expect(validateParametricCaseV1(c).status).toBe('valid'); c.pusherTubeRadius = 2.0; expect(validateParametricCaseV1(c).errors).toContain('pusherTubeRadius must not exceed pusherBossRadius'); c.pusherCount = 3; expect(validateParametricCaseV1(c).status).toBe('invalid'); }); });

const pusher = (): ParametricPusherV1 => ({ schema: 'parametric-pusher/v1', angularPositionDeg: 60, tubeRadius: 0.9, tubeLength: 1.8, tubeEmbed: 1.2, bossRadius: 1.4, bossLength: 1, bossEmbed: 1.2, headDiameterMm: 2.8, headLengthMm: 1.5, stemDiameterMm: 0.8 });
describe('standalone pusher contract', () => { it('validates dimensions and preserves unknown status', () => { expect(validateParametricPusherV1(pusher()).status).toBe('valid'); const unknown = pusher(); unknown.stemDiameterMm = u; expect(validateParametricPusherV1(unknown).status).toBe('unknown'); const invalid = pusher(); invalid.tubeRadius = 2; expect(validateParametricPusherV1(invalid).errors).toContain('tubeRadius must not exceed bossRadius'); }); });

const dial = (): ParametricDialV1 => ({ schema: 'parametric-dial/v1', outerDiameterMm: 32, thicknessMm: 0.4, centreHoleDiameterMm: 1.5, markerLayout: { kind: 'baton', count: 12, startAngleDeg: -90, radiusInnerMm: 11.5, radiusOuterMm: 14.2, widthMm: 0.5, applied: true, printed: true, lumed: true }, windows: [{ kind: 'date', angleDeg: 90, widthMm: 3.5, heightMm: 1.4, cornerRadiusMm: 0.25 }], subdials: [{ role: 'chronograph-seconds', angleDeg: 180, radiusMm: 3.2, handRadiusMm: 2.4, markerCount: 12 }], surface: { color: '#0f172a', secondaryColor: '#020617', finish: 'textured', texture: { kind: 'clous-de-paris', intensity: 0.72, contrast: 0.74 } }, provenance: { status: 'provisional', source: 'test fixture' } });
describe('parametric dial contract', () => { it('supports markings, subdials, windows and texture metadata', () => { expect(validateParametricDialV1(dial()).status).toBe('valid'); const invalid = dial(); invalid.markerLayout.radiusOuterMm = 20; expect(validateParametricDialV1(invalid).status).toBe('invalid'); }); });
